name: Push loc

on:
    workflow_dispatch:

jobs:
    push-loc:
        runs-on: ubuntu-latest
        steps:
            - name: Checkout
              uses: actions/checkout@v4

            - name: Install loc dependencies
              working-directory: ./scripts/loc
              run: npm install

            - name: Install Crowdin CLI
              run: npm i -g @crowdin/cli

            - name: Push loc
              working-directory: ./scripts/loc
              env:
                  CROWDIN_API_TOKEN: ${{ secrets.CROWDIN_API_TOKEN }}
              run: ./push-new-source-strings
