name: Release Firefox Build

on:
    workflow_dispatch:
        inputs:
            releaseTag:
                description: 'Release tag'
                required: true
                type: string
jobs:
    submit:
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v4
              with:
                  ref: ${{ inputs.releaseTag }}
            - uses: actions/setup-node@v3
              with:
                  node-version: 22
                  cache: 'npm'
            - run: npm install --global yarn
            - run: yarn set version 3.2.0
            - run: yarn install
            - run: yarn workspace @project/extension run zip:firefox
            - name: Submit to stores
              working-directory: ./extension
              run: |
                  yarn run wxt submit \
                    --firefox-zip .output/*-firefox.zip --firefox-sources-zip .output/*-sources.zip \
                    --firefox-channel unlisted
              env:
                  FIREFOX_EXTENSION_ID: e4b27483-2e73-4762-b2ec-8d988a143a40
                  FIREFOX_JWT_ISSUER: ${{ secrets.FIREFOX_JWT_ISSUER }}
                  FIREFOX_JWT_SECRET: ${{ secrets.FIREFOX_JWT_SECRET }}
